Repository Happiness-Meta/final-back, pull requests merged in 2024-03, with the labels that each got.

#29 Fix: SecurityContext에 User가 담기지 않는 문제 해결
  src/main/java/org/happinessmeta/last/user/domain/User.java
  src/main/java/org/happinessmeta/last/user/repository/UserRepository.java
  src/main/java/org/happinessmeta/last/user/service/UserService.java
Labels: bug

#35 Jason login
  .github/pull_request_template.md
  src/main/java/org/happinessmeta/last/common/security/SecurityConfig.java
Labels: Docs, Feat

#44 Fix: JPA DDL 에러
  src/main/java/org/happinessmeta/last/portfolio/domain/entity/PortfolioComponent.java
  src/main/java/org/happinessmeta/last/portfolio/domain/entity/ProblemAndSolution.java
  src/main/java/org/happinessmeta/last/portfolio/domain/entity/ProjectFunction.java
  src/main/java/org/happinessmeta/last/portfolio/domain/entity/RefLink.java
  src/main/java/org/happinessmeta/last/resume/domain/entity/Resume.java
  src/main/java/org/happinessmeta/last/user/domain/User.java
Labels: BugFix

#48 Feat: 중복 로그인 제한, 로그아웃 기능 구현
  src/main/java/org/happinessmeta/last/auth/dto/RegisterResponse.java
  src/main/java/org/happinessmeta/last/auth/service/AuthenticationService.java
  src/main/java/org/happinessmeta/last/common/exception/TokenNotFoundException.java
  src/main/java/org/happinessmeta/last/common/security/JwtAuthenticationFilter.java
  src/main/java/org/happinessmeta/last/common/security/LogoutService.java
  src/main/java/org/happinessmeta/last/common/security/SecurityConfig.java
  src/main/java/org/happinessmeta/last/token/Token.java
  src/main/java/org/happinessmeta/last/token/TokenRepository.java
  src/main/java/org/happinessmeta/last/token/TokenType.java
  src/main/java/org/happinessmeta/last/user/domain/User.java
Labels: Feat

#55 Feat: OrderResponse DTO 추가, Payment 필드 추가( 카드 번호, 카드사 등 )
  src/main/java/org/happinessmeta/last/payment/controller/OrderController.java
  src/main/java/org/happinessmeta/last/payment/controller/PaymentController.java
  src/main/java/org/happinessmeta/last/payment/domain/Payment.java
  src/main/java/org/happinessmeta/last/payment/dto/OrderResponse.java
  src/main/java/org/happinessmeta/last/payment/dto/PaymentCallbackRequest.java
  src/main/java/org/happinessmeta/last/payment/repository/PaymentRepository.java
  src/main/java/org/happinessmeta/last/payment/service/OrderService.java
  src/main/java/org/happinessmeta/last/payment/service/PaymentService.java
Labels: Feat

#59 Feat: Scheduled 어노테이션을 통하여 결제 대기 상태의 데이터 삭제 기능 추가
  src/main/java/org/happinessmeta/last/FinalApplication.java
  src/main/java/org/happinessmeta/last/payment/controller/OrderController.java
  src/main/java/org/happinessmeta/last/payment/domain/Order.java
  src/main/java/org/happinessmeta/last/payment/repository/OrderRepository.java
  src/main/java/org/happinessmeta/last/payment/service/OrderService.java
Labels: Feat
